"""adding name column to domiciles

Revision ID: 1735b52d0694
Revises: ab1eec50112c
Create Date: 2023-03-30 11:43:50.809543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1735b52d0694'
down_revision = 'ab1eec50112c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Domiciles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Domiciles', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
