"""Adding Column Called reason to visit

Revision ID: 970eb4552e3d
Revises: ab1eec50112c
Create Date: 2023-03-29 18:49:21.865579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970eb4552e3d'
down_revision = 'ab1eec50112c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domicile_travelers')
    with op.batch_alter_table('Vacations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsn_for_visit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vacations', schema=None) as batch_op:
        batch_op.drop_column('rsn_for_visit')

    op.create_table('domicile_travelers',
    sa.Column('Domicile_id', sa.INTEGER(), nullable=False),
    sa.Column('Traveler_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['Domicile_id'], ['Domiciles.id'], ),
    sa.ForeignKeyConstraint(['Traveler_id'], ['Travelers.id'], ),
    sa.PrimaryKeyConstraint('Domicile_id', 'Traveler_id')
    )
    # ### end Alembic commands ###
