"""Created Classes and Build out Seed File

Revision ID: ab1eec50112c
Revises: ea7be3db4b04
Create Date: 2023-03-28 08:50:35.998772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1eec50112c'
down_revision = 'ea7be3db4b04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
