"""Added Vacation model

Revision ID: c810dd035d84
Revises: 0196a1a12f37
Create Date: 2023-03-27 10:52:27.153922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c810dd035d84'
down_revision = '0196a1a12f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Domiciles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('Domiciles', sa.Column('sleep_capacity', sa.Integer(), nullable=True))
    op.add_column('Domiciles', sa.Column('local_amenities', sa.String(), nullable=True))
    op.add_column('Domiciles', sa.Column('property_type', sa.String(), nullable=True))
    op.add_column('Travelers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('Travelers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('Travelers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('Vacations', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('Vacations', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('Vacations', sa.Column('Traveler_id', sa.Integer(), nullable=True))
    op.add_column('Vacations', sa.Column('Domicile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Vacations', 'Domiciles', ['Domicile_id'], ['id'])
    op.create_foreign_key(None, 'Vacations', 'Travelers', ['Traveler_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vacations', type_='foreignkey')
    op.drop_constraint(None, 'Vacations', type_='foreignkey')
    op.drop_column('Vacations', 'Domicile_id')
    op.drop_column('Vacations', 'Traveler_id')
    op.drop_column('Vacations', 'end_date')
    op.drop_column('Vacations', 'start_date')
    op.drop_column('Travelers', 'location')
    op.drop_column('Travelers', 'last_name')
    op.drop_column('Travelers', 'first_name')
    op.drop_column('Domiciles', 'property_type')
    op.drop_column('Domiciles', 'local_amenities')
    op.drop_column('Domiciles', 'sleep_capacity')
    op.drop_column('Domiciles', 'location')
    # ### end Alembic commands ###
